export { default as HeroSection, type HeroSectionProps } from "./HeroSection";
export { default as StorySection, type StorySectionProps } from "./StorySection";
export { default as WhyGayaSection } from "./WhyGayaSection";
export { default as JourneySection, type JourneyStep } from "./JourneySection";
export { default as TimelineSection, type TimelineSectionProps } from "./TimelineSection";
export { default as ServicesSection, type ServicesSectionProps } from "./ServicesSection";
export { default as EmotionGallerySection, type EmotionGallerySectionProps } from "./EmotionGallerySection";
export { default as DestinationsSection, type DestinationsSectionProps } from "./DestinationsSection";
export { default as GallerySection, type GallerySectionProps, type GalleryItem } from "./GallerySection";
export { default as FAQSection, type FAQSectionProps } from "./FAQSection";
export { default as TestimonialsSection, type TestimonialsSectionProps } from "./TestimonialsSection";
export { default as CTASection, type CTASectionProps } from "./CTASection";
export { default as StatisticsSection, type StatisticsSectionProps } from "./StatisticsSection";
export { default as StatsSection } from "./StatisticsSection";
export { default as SacredPlacesSection } from "./SacredPlacesSection";
export { default as HotelsSection } from "./HotelsSection";
export { default as TransportationSection } from "./TransportationSection";
export { default as WhyChooseUsSection } from "./WhyChooseUsSection";
export { default as SacredTrustSection, type SacredTrustSectionProps } from "./SacredTrustSection";
export { default as BlogsSection } from "./BlogsSection";
export { default as BlogSection } from "./BlogsSection";
export { default as ContactSection, type ContactSectionProps } from "./ContactSection";
export { default as TrustCenterSection, type TrustCenterSectionProps } from "./TrustCenterSection";
